[ 2017-04-07 14:33:37.6827 41629/0x7fff78f26000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-04-07 14:33:37.7017 41631/0x7fff78f26000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-04-07 14:33:37.7030 41631/0x7fff78f26000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-04-07 14:33:37.7092 41631/0x7fff78f26000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 41631
[ 2017-04-07 14:33:37.7177 41633/0x7fff78f26000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-04-07 14:33:37.7192 41633/0x7fff78f26000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 41633
App 41646 stdout: 
App 41646 stderr: Traceback (most recent call last):
App 41646 stderr:   File "/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py", line 325, in <module>
App 41646 stderr:     app_module = load_app()
App 41646 stderr:   File "/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py", line 62, in load_app
App 41646 stderr:     
App 41646 stderr: return imp.load_source('passenger_wsgi', startup_file)
App 41646 stderr:   File "/Users/alan/sites/combogames/passenger_wsgi.py", line 7, in <module>
App 41646 stderr:     from app import MyApp as application
App 41646 stderr:   File "/Users/alan/Sites/combogames/app.py", line 1, in <module>
App 41646 stderr:     from flask import Flask, render_template, jsonify, request
App 41646 stderr: ImportError: No module named flask
[ 2017-04-07 14:33:40.5147 41631/0x7000006eb000 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /Users/alan/sites/combogames: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: 1334c317
  Error details saved to: /var/folders/tc/3j3_rt196d7_fz2y5xbz1k1c0000gn/T//passenger-error-HXsI5z.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py&quot;, line 325, in &lt;module&gt;
    app_module = load_app()
  File &quot;/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py&quot;, line 62, in load_app
    return imp.load_source(&apos;passenger_wsgi&apos;, startup_file)
  File &quot;/Users/alan/sites/combogames/passenger_wsgi.py&quot;, line 7, in &lt;module&gt;
    from app import MyApp as application
  File &quot;/Users/alan/Sites/combogames/app.py&quot;, line 1, in &lt;module&gt;
    from flask import Flask, render_template, jsonify, request
ImportError: No module named flask
</pre>

[ 2017-04-07 14:33:40.5547 41631/0x70000018a000 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 1334c317. Please see earlier logs for details about the error.


[ 2017-04-07 14:33:48.3396 41631/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:33:48.3396 41633/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:33:48.3397 41633/0x7fff78f26000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:33:48.3397 41631/0x7fff78f26000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:33:48.3398 41633/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-04-07 14:33:48.3398 41633/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-04-07 14:33:48.3398 41633/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-04-07 14:33:48.3399 41631/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-04-07 14:33:48.3400 41631/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-04-07 14:33:48.3400 41631/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-04-07 14:33:48.3400 41631/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-04-07 14:33:48.3402 41631/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-04-07 14:33:48.3402 41631/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-04-07 14:33:48.3402 41631/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-04-07 14:33:48.3403 41631/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-04-07 14:33:48.3404 41631/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-04-07 14:33:48.3404 41631/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-04-07 14:33:48.3411 41633/0x7fff78f26000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-04-07 14:33:48.3556 41631/0x7fff78f26000 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-04-07 14:34:02.9647 41678/0x7fff78f26000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-04-07 14:34:02.9829 41680/0x7fff78f26000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-04-07 14:34:02.9845 41680/0x7fff78f26000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-04-07 14:34:02.9907 41680/0x7fff78f26000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 41680
[ 2017-04-07 14:34:02.9993 41682/0x7fff78f26000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-04-07 14:34:03.0010 41682/0x7fff78f26000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 41682
App 41694 stdout: 
App 41694 stderr: Traceback (most recent call last):
App 41694 stderr:   File "/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py", line 325, in <module>
App 41694 stderr:     app_module = load_app()
App 41694 stderr:   File "/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py", line 62, in load_app
App 41694 stderr:     return imp.load_source('passenger_wsgi', startup_file)
App 41694 stderr:   File "/Users/alan/sites/combogames/passenger_wsgi.py", line 7, in <module>
App 41694 stderr:     from app import MyApp as application
App 41694 stderr:   File "/Users/alan/Sites/combogames/app.py", line 2, in <module>
App 41694 stderr:     from comboGame import *
App 41694 stderr:   File "/Users/alan/Sites/combogames/comboGame.py", line 2, in <module>
App 41694 stderr:     from flaskext.mysql import MySQL
App 41694 stderr: ImportError: No module named flaskext.mysql
[ 2017-04-07 14:34:05.4934 41680/0x7000006eb000 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /Users/alan/sites/combogames: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: 3ad93d53
  Error details saved to: /var/folders/tc/3j3_rt196d7_fz2y5xbz1k1c0000gn/T//passenger-error-wPwDyZ.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py&quot;, line 325, in &lt;module&gt;
    app_module = load_app()
  File &quot;/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py&quot;, line 62, in load_app
    return imp.load_source(&apos;passenger_wsgi&apos;, startup_file)
  File &quot;/Users/alan/sites/combogames/passenger_wsgi.py&quot;, line 7, in &lt;module&gt;
    from app import MyApp as application
  File &quot;/Users/alan/Sites/combogames/app.py&quot;, line 2, in &lt;module&gt;
    from comboGame import *
  File &quot;/Users/alan/Sites/combogames/comboGame.py&quot;, line 2, in &lt;module&gt;
    from flaskext.mysql import MySQL
ImportError: No module named flaskext.mysql
</pre>

[ 2017-04-07 14:34:05.4997 41680/0x70000018a000 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 3ad93d53. Please see earlier logs for details about the error.


[ 2017-04-07 14:34:09.3633 41680/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:34:09.3633 41682/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:34:09.3633 41680/0x7fff78f26000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:34:09.3633 41682/0x7fff78f26000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:34:09.3634 41682/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-04-07 14:34:09.3634 41682/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-04-07 14:34:09.3634 41682/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-04-07 14:34:09.3634 41680/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-04-07 14:34:09.3635 41680/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-04-07 14:34:09.3635 41680/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-04-07 14:34:09.3636 41680/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-04-07 14:34:09.3636 41680/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-04-07 14:34:09.3636 41680/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-04-07 14:34:09.3636 41680/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-04-07 14:34:09.3635 41680/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-04-07 14:34:09.3637 41680/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-04-07 14:34:09.3637 41680/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-04-07 14:34:09.3641 41682/0x7fff78f26000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-04-07 14:34:09.3764 41680/0x7fff78f26000 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-04-07 14:34:40.6273 41732/0x7fff78f26000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-04-07 14:34:40.6455 41734/0x7fff78f26000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-04-07 14:34:40.6470 41734/0x7fff78f26000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-04-07 14:34:40.6534 41734/0x7fff78f26000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 41734
[ 2017-04-07 14:34:40.6619 41736/0x7fff78f26000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-04-07 14:34:40.6634 41736/0x7fff78f26000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 41736
App 41748 stdout: 
App 41748 stderr: [2017-04-07 14:34:50,738] ERROR in app: Exception on /_gales_nim [GET]
App 41748 stderr: Traceback (most recent call last):
App 41748 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 41748 stderr:     response = self.full_dispatch_request()
App 41748 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 41748 stderr:     rv = self.handle_user_exception(e)
App 41748 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 41748 stderr:     reraise(exc_type, exc_value, tb)
App 41748 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 41748 stderr:     rv = self.dispatch_request()
App 41748 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 41748 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 41748 stderr:   File "/Users/alan/Sites/combogames/app.py", line 202, in gales_nim
App 41748 stderr:     conn = mysql.connect()
App 41748 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 41748 stderr:     return pymysql.connect(**self.connect_args)
App 41748 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 41748 stderr:     return Connection(*args, **kwargs)
App 41748 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 41748 stderr:     self.connect()
App 41748 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 963, in connect
App 41748 stderr:     raise exc
App 41748 stderr: OperationalError: (2003, "Can't connect to MySQL server on '***' ([Errno 8] nodename nor servname provided, or not known)")


[ 2017-04-07 14:34:56.6448 41734/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:34:56.6448 41736/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:34:56.6449 41734/0x7fff78f26000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:34:56.6449 41736/0x7fff78f26000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:34:56.6449 41734/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 41748, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 14:34:56.6450 41736/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-04-07 14:34:56.6450 41736/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-04-07 14:34:56.6449 41736/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-04-07 14:34:56.6452 41734/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-04-07 14:34:56.6452 41734/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-04-07 14:34:56.6457 41736/0x7fff78f26000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-04-07 14:34:56.6460 41734/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-04-07 14:34:56.6461 41734/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-04-07 14:34:56.6461 41734/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-04-07 14:34:56.6460 41734/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-04-07 14:34:56.6462 41734/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-04-07 14:34:56.6462 41734/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-04-07 14:34:56.6462 41734/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-04-07 14:34:56.6462 41734/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-04-07 14:34:56.6463 41734/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 41748, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 14:34:56.7642 41734/0x7fff78f26000 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-04-07 14:35:34.5023 41784/0x7fff78f26000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-04-07 14:35:34.5212 41786/0x7fff78f26000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-04-07 14:35:34.5227 41786/0x7fff78f26000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-04-07 14:35:34.5288 41786/0x7fff78f26000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 41786
[ 2017-04-07 14:35:34.5371 41788/0x7fff78f26000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-04-07 14:35:34.5386 41788/0x7fff78f26000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 41788
App 41799 stdout: 
App 41799 stderr: [2017-04-07 14:35:39,962] ERROR in app: Exception on /_gales_nim [GET]
App 41799 stderr: Traceback (most recent call last):
App 41799 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 41799 stderr:     response = self.full_dispatch_request()
App 41799 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 41799 stderr:     rv = self.handle_user_exception(e)
App 41799 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 41799 stderr:     reraise(exc_type, exc_value, tb)
App 41799 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 41799 stderr:     rv = self.dispatch_request()
App 41799 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 41799 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 41799 stderr:   File "/Users/alan/Sites/combogames/app.py", line 202, in gales_nim
App 41799 stderr:     conn = mysql.connect()
App 41799 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 41799 stderr:     return pymysql.connect(**self.connect_args)
App 41799 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 41799 stderr:     return Connection(*args, **kwargs)
App 41799 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 41799 stderr:     self.connect()
App 41799 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 41799 stderr:     self._request_authentication()
App 41799 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 41799 stderr:     auth_packet = self._read_packet()
App 41799 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 41799 stderr:     packet.check_error()
App 41799 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 41799 stderr:     err.raise_mysql_exception(self._data)
App 41799 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 41799 stderr:     raise errorclass(errno, errval)
App 41799 stderr: OperationalError: (1044, u"Access denied for user 'combogames'@'192.83.228.245' to database 'NimValues'")

[ 2017-04-07 14:35:42.9520 41788/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:35:42.9520 41788/0x7fff78f26000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...

[ 2017-04-07 14:35:42.9520 41786/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:35:42.9521 41786/0x7fff78f26000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:35:42.9521 41788/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-04-07 14:35:42.9521 41788/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-04-07 14:35:42.9521 41788/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-04-07 14:35:42.9521 41786/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 41799, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 14:35:42.9523 41786/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-04-07 14:35:42.9523 41786/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-04-07 14:35:42.9523 41786/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-04-07 14:35:42.9523 41786/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-04-07 14:35:42.9524 41786/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-04-07 14:35:42.9524 41786/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-04-07 14:35:42.9525 41786/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-04-07 14:35:42.9525 41786/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-04-07 14:35:42.9525 41786/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-04-07 14:35:42.9525 41786/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-04-07 14:35:42.9526 41786/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 41799, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 14:35:42.9529 41788/0x7fff78f26000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-04-07 14:35:43.0697 41786/0x7fff78f26000 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-04-07 14:38:41.3222 41859/0x7fff78f26000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-04-07 14:38:41.3424 41861/0x7fff78f26000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-04-07 14:38:41.3439 41861/0x7fff78f26000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-04-07 14:38:41.3504 41861/0x7fff78f26000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 41861
[ 2017-04-07 14:38:41.3590 41863/0x7fff78f26000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-04-07 14:38:41.3608 41863/0x7fff78f26000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 41863
App 41875 stdout: 
App 41875 stderr: [2017-04-07 14:38:49,261] ERROR in app: Exception on /_gales_nim [GET]
App 41875 stderr: Traceback (most recent call last):
App 41875 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 41875 stderr:     response = self.full_dispatch_request()
App 41875 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 41875 stderr:     rv = self.handle_user_exception(e)
App 41875 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 41875 stderr:     reraise(exc_type, exc_value, tb)
App 41875 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 41875 stderr:     rv = self.dispatch_request()
App 41875 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 41875 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 41875 stderr:   File "/Users/alan/Sites/combogames/app.py", line 208, in gales_nim
App 41875 stderr:     thenimvalue = game.getNimValue()
App 41875 stderr:   File "/Users/alan/Sites/combogames/comboGame.py", line 109, in getNimValue
App 41875 stderr:     if len(self.game) == size:
App 41875 stderr: NameError: global name 'size' is not defined


[ 2017-04-07 14:38:51.8929 41863/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:38:51.8930 41861/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:38:51.8930 41863/0x7fff78f26000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:38:51.8930 41861/0x7fff78f26000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:38:51.8931 41861/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 41875, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 14:38:51.8931 41863/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-04-07 14:38:51.8931 41863/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-04-07 14:38:51.8932 41863/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-04-07 14:38:51.8933 41861/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-04-07 14:38:51.8934 41861/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-04-07 14:38:51.8935 41861/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-04-07 14:38:51.8936 41861/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-04-07 14:38:51.8934 41861/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-04-07 14:38:51.8936 41861/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-04-07 14:38:51.8936 41861/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-04-07 14:38:51.8936 41861/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-04-07 14:38:51.8938 41861/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-04-07 14:38:51.8938 41861/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-04-07 14:38:51.8939 41861/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 41875, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 14:38:51.8948 41863/0x7fff78f26000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-04-07 14:38:52.0146 41861/0x7fff78f26000 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-04-07 14:39:21.9260 41904/0x7fff78f26000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-04-07 14:39:21.9460 41906/0x7fff78f26000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-04-07 14:39:21.9476 41906/0x7fff78f26000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-04-07 14:39:21.9537 41906/0x7fff78f26000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 41906
[ 2017-04-07 14:39:21.9623 41908/0x7fff78f26000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-04-07 14:39:21.9642 41908/0x7fff78f26000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 41908
App 41922 stdout: 
App 41922 stderr: [2017-04-07 14:40:17,402] ERROR in app: Exception on /_gales_nim [GET]
App 41922 stderr: Traceback (most recent call last):
App 41922 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 41922 stderr:     response = self.full_dispatch_request()
App 41922 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 41922 stderr:     rv = self.handle_user_exception(e)
App 41922 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 41922 stderr:     reraise(exc_type, exc_value, tb)
App 41922 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 41922 stderr:     rv = self.dispatch_request()
App 41922 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 41922 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 41922 stderr:   File "/Users/alan/Sites/combogames/app.py", line 208, in gales_nim
App 41922 stderr:     thenimvalue = game.getNimValue()
App 41922 stderr:   File "/Users/alan/Sites/combogames/comboGame.py", line 112, in getNimValue
App 41922 stderr:     newnimvalue = self.mexMoves()
App 41922 stderr:   File "/Users/alan/Sites/combogames/comboGame.py", line 38, in mexMoves
App 41922 stderr:     self.getPossibleMoves()
App 41922 stderr:   File "/Users/alan/Sites/combogames/comboGame.py", line 132, in getPossibleMoves
App 41922 stderr:     moves.append(GalesNim(newlist))
App 41922 stderr: TypeError: __init__() takes exactly 3 arguments (2 given)


[ 2017-04-07 14:40:21.9600 41906/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:40:21.9600 41908/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:40:21.9601 41908/0x7fff78f26000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:40:21.9601 41906/0x7fff78f26000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:40:21.9601 41906/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 41922, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 14:40:21.9601 41908/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-04-07 14:40:21.9601 41908/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-04-07 14:40:21.9601 41908/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-04-07 14:40:21.9602 41906/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-04-07 14:40:21.9603 41906/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-04-07 14:40:21.9603 41906/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-04-07 14:40:21.9603 41906/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-04-07 14:40:21.9604 41906/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-04-07 14:40:21.9604 41906/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-04-07 14:40:21.9605 41906/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-04-07 14:40:21.9605 41906/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-04-07 14:40:21.9606 41906/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-04-07 14:40:21.9606 41906/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-04-07 14:40:21.9607 41906/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 41922, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 14:40:21.9619 41908/0x7fff78f26000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-04-07 14:40:22.0772 41906/0x7fff78f26000 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-04-07 14:40:39.0422 41984/0x7fff78f26000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-04-07 14:40:39.0609 41987/0x7fff78f26000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-04-07 14:40:39.0628 41987/0x7fff78f26000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-04-07 14:40:39.0694 41987/0x7fff78f26000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 41987
[ 2017-04-07 14:40:39.0796 41989/0x7fff78f26000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-04-07 14:40:39.0815 41989/0x7fff78f26000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 41989
App 42001 stdout: 
App 42001 stderr: [2017-04-07 14:40:42,072] ERROR in app: Exception on /_gales_nim [GET]
App 42001 stderr: Traceback (most recent call last):
App 42001 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 42001 stderr:     response = self.full_dispatch_request()
App 42001 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 42001 stderr:     rv = self.handle_user_exception(e)
App 42001 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 42001 stderr:     reraise(exc_type, exc_value, tb)
App 42001 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 42001 stderr:     rv = self.dispatch_request()
App 42001 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 42001 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 42001 stderr:   File "/Users/alan/Sites/combogames/app.py", line 208, in gales_nim
App 42001 stderr:     thenimvalue = game.getNimValue()
App 42001 stderr:   File "/Users/alan/Sites/combogames/comboGame.py", line 112, in getNimValue
App 42001 stderr:     newnimvalue = self.mexMoves()
App 42001 stderr:   File "/Users/alan/Sites/combogames/comboGame.py", line 38, in mexMoves
App 42001 stderr:     self.getPossibleMoves()
App 42001 stderr:   File "/Users/alan/Sites/combogames/comboGame.py", line 137, in getPossibleMoves
App 42001 stderr:     moves.append(GalesNim(newlist))
App 42001 stderr: TypeError: __init__() takes exactly 3 arguments (2 given)


[ 2017-04-07 14:40:55.0833 41987/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:40:55.0833 41989/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:40:55.0833 41989/0x7fff78f26000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:40:55.0833 41987/0x7fff78f26000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:40:55.0833 41987/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 42001, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 14:40:55.0834 41989/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-04-07 14:40:55.0834 41989/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-04-07 14:40:55.0835 41989/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-04-07 14:40:55.0835 41987/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-04-07 14:40:55.0836 41987/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-04-07 14:40:55.0837 41987/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-04-07 14:40:55.0837 41987/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-04-07 14:40:55.0839 41987/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-04-07 14:40:55.0839 41987/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-04-07 14:40:55.0839 41987/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-04-07 14:40:55.0839 41987/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-04-07 14:40:55.0840 41987/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-04-07 14:40:55.0841 41987/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-04-07 14:40:55.0841 41987/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 42001, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 14:40:55.0851 41989/0x7fff78f26000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-04-07 14:40:55.2024 41987/0x7fff78f26000 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-04-07 14:40:55.6637 42034/0x7fff78f26000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-04-07 14:40:55.6869 42036/0x7fff78f26000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-04-07 14:40:55.6882 42036/0x7fff78f26000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-04-07 14:40:55.6961 42036/0x7fff78f26000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 42036
[ 2017-04-07 14:40:55.7064 42038/0x7fff78f26000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-04-07 14:40:55.7089 42038/0x7fff78f26000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 42038
App 42050 stdout: 


[ 2017-04-07 14:41:15.7550 42038/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:41:15.7550 42036/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 14:41:15.7551 42038/0x7fff78f26000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:41:15.7551 42036/0x7fff78f26000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 14:41:15.7551 42036/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 42050, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 14:41:15.7551 42038/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-04-07 14:41:15.7551 42038/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-04-07 14:41:15.7551 42038/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-04-07 14:41:15.7553 42036/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-04-07 14:41:15.7553 42036/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-04-07 14:41:15.7553 42036/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-04-07 14:41:15.7554 42036/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-04-07 14:41:15.7554 42036/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-04-07 14:41:15.7554 42036/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-04-07 14:41:15.7554 42036/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-04-07 14:41:15.7554 42036/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-04-07 14:41:15.7555 42036/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-04-07 14:41:15.7556 42036/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-04-07 14:41:15.7557 42036/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 42050, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 14:41:15.7558 42038/0x7fff78f26000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-04-07 14:41:15.8706 42036/0x7fff78f26000 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-04-07 14:41:16.4358 42084/0x7fff78f26000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-04-07 14:41:16.4553 42086/0x7fff78f26000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-04-07 14:41:16.4570 42086/0x7fff78f26000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-04-07 14:41:16.4633 42086/0x7fff78f26000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 42086
[ 2017-04-07 14:41:16.4718 42088/0x7fff78f26000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-04-07 14:41:16.4740 42088/0x7fff78f26000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 42088
App 42103 stdout: 


[ 2017-04-07 15:55:52.2273 42086/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 15:55:52.2274 42088/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-04-07 15:55:52.2274 42086/0x7fff78f26000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 15:55:52.2274 42088/0x7fff78f26000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-04-07 15:55:52.2274 42086/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 42103, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 15:55:52.2275 42088/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-04-07 15:55:52.2275 42088/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-04-07 15:55:52.2275 42088/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-04-07 15:55:52.2276 42086/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-04-07 15:55:52.2277 42086/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-04-07 15:55:52.2278 42086/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-04-07 15:55:52.2278 42086/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-04-07 15:55:52.2279 42086/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-04-07 15:55:52.2279 42086/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-04-07 15:55:52.2279 42086/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-04-07 15:55:52.2280 42086/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-04-07 15:55:52.2280 42086/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-04-07 15:55:52.2280 42086/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-04-07 15:55:52.2281 42086/0x7fff78f26000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 42103, application /Users/alan/sites/combogames/public (development)
[ 2017-04-07 15:55:52.2283 42088/0x7fff78f26000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished

[ 2017-04-07 15:55:52.2301 42086/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 1 more time(s) to force shutdown)
[ 2017-05-09 11:42:29.7955 5852/0x7fff7a818000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-05-09 11:42:29.8160 5854/0x7fff7a818000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-05-09 11:42:29.8177 5854/0x7fff7a818000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-05-09 11:42:29.8251 5854/0x7fff7a818000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 5854
[ 2017-05-09 11:42:29.8345 5856/0x7fff7a818000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-05-09 11:42:29.8365 5856/0x7fff7a818000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 5856
App 5870 stdout: 


[ 2017-05-09 11:44:13.8193 5856/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-05-09 11:44:13.8193 5854/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-05-09 11:44:13.8193 5856/0x7fff7a818000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-05-09 11:44:13.8193 5854/0x7fff7a818000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-05-09 11:44:13.8194 5854/0x7fff7a818000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 5870, application /Users/alan/sites/combogames/public (development)
[ 2017-05-09 11:44:13.8194 5856/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-05-09 11:44:13.8195 5856/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-05-09 11:44:13.8195 5856/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-05-09 11:44:13.8198 5854/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-05-09 11:44:13.8199 5854/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-05-09 11:44:13.8204 5856/0x7fff7a818000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-05-09 11:44:13.8205 5854/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-05-09 11:44:13.8205 5854/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-05-09 11:44:13.8206 5854/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-05-09 11:44:13.8206 5854/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-05-09 11:44:13.8206 5854/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-05-09 11:44:13.8206 5854/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-05-09 11:44:13.8207 5854/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-05-09 11:44:13.8207 5854/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-05-09 11:44:13.8210 5854/0x7fff7a818000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 5870, application /Users/alan/sites/combogames/public (development)
[ 2017-05-09 11:44:13.9392 5854/0x7fff7a818000 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-05-09 11:44:14.7822 5958/0x7fff7a818000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-05-09 11:44:14.7998 5960/0x7fff7a818000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-05-09 11:44:14.8011 5960/0x7fff7a818000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-05-09 11:44:14.8074 5960/0x7fff7a818000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 5960
[ 2017-05-09 11:44:14.8154 5962/0x7fff7a818000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-05-09 11:44:14.8169 5962/0x7fff7a818000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 5962
App 5974 stdout: 
App 5974 stderr: Traceback (most recent call last):
App 5974 stderr:   File "/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py", line 325, in <module>
App 5974 stderr:     app_module = load_app()
App 5974 stderr:   File "/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py", line 62, in load_app
App 5974 stderr:     return imp.load_source('passenger_wsgi', startup_file)
App 5974 stderr:   File "/Users/alan/sites/combogames/passenger_wsgi.py", line 7, in <module>
App 5974 stderr:     from app import MyApp as application
App 5974 stderr:   File "/Users/alan/Sites/combogames/app.py", line 23, in <module>
App 5974 stderr:     @MyApp.route("test")
App 5974 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1080, in decorator
App 5974 stderr:     self.add_url_rule(rule, endpoint, f, **options)
App 5974 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 64, in wrapper_func
App 5974 stderr:     return f(self, *args, **kwargs)
App 5974 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1043, in add_url_rule
App 5974 stderr:     rule = self.url_rule_class(rule, methods=methods, **options)
App 5974 stderr:   File "/usr/local/lib/python2.7/site-packages/werkzeug/routing.py", line 603, in __init__
App 5974 stderr:     raise ValueError('urls must start with a leading slash')
App 5974 stderr: ValueError: urls must start with a leading slash
[ 2017-05-09 11:44:17.4105 5960/0x7000006eb000 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /Users/alan/sites/combogames: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: c0f443fc
  Error details saved to: /var/folders/tc/3j3_rt196d7_fz2y5xbz1k1c0000gn/T//passenger-error-x5Uuw4.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py&quot;, line 325, in &lt;module&gt;
    app_module = load_app()
  File &quot;/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py&quot;, line 62, in load_app
    return imp.load_source(&apos;passenger_wsgi&apos;, startup_file)
  File &quot;/Users/alan/sites/combogames/passenger_wsgi.py&quot;, line 7, in &lt;module&gt;
    from app import MyApp as application
  File &quot;/Users/alan/Sites/combogames/app.py&quot;, line 23, in &lt;module&gt;
    @MyApp.route(&quot;test&quot;)
  File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 1080, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 1043, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File &quot;/usr/local/lib/python2.7/site-packages/werkzeug/routing.py&quot;, line 603, in __init__
    raise ValueError(&apos;urls must start with a leading slash&apos;)
ValueError: urls must start with a leading slash
</pre>

[ 2017-05-09 11:44:17.4179 5960/0x70000018a000 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is c0f443fc. Please see earlier logs for details about the error.
App 5985 stdout: 
App 5985 stderr: Traceback (most recent call last):
App 5985 stderr:   File "/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py", line 325, in <module>
App 5985 stderr:     app_module = load_app()
App 5985 stderr:   File "/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py", line 62, in load_app
App 5985 stderr:     return imp.load_source('passenger_wsgi', startup_file)
App 5985 stderr:   File "/Users/alan/sites/combogames/passenger_wsgi.py", line 7, in <module>
App 5985 stderr:     from app import MyApp as application
App 5985 stderr:   File "/Users/alan/Sites/combogames/app.py", line 23, in <module>
App 5985 stderr:     @MyApp.route("test")
App 5985 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1080, in decorator
App 5985 stderr:     self.add_url_rule(rule, endpoint, f, **options)
App 5985 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 64, in wrapper_func
App 5985 stderr:     return f(self, *args, **kwargs)
App 5985 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1043, in add_url_rule
App 5985 stderr:     rule = self.url_rule_class(rule, methods=methods, **options)
App 5985 stderr:   File "/usr/local/lib/python2.7/site-packages/werkzeug/routing.py", line 603, in __init__
App 5985 stderr:     raise ValueError('urls must start with a leading slash')
App 5985 stderr: ValueError: urls must start with a leading slash
[ 2017-05-09 11:44:18.2475 5960/0x7000006eb000 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /Users/alan/sites/combogames: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: 067b3206
  Error details saved to: /var/folders/tc/3j3_rt196d7_fz2y5xbz1k1c0000gn/T//passenger-error-SoEDU6.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py&quot;, line 325, in &lt;module&gt;
    app_module = load_app()
  File &quot;/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py&quot;, line 62, in load_app
    return imp.load_source(&apos;passenger_wsgi&apos;, startup_file)
  File &quot;/Users/alan/sites/combogames/passenger_wsgi.py&quot;, line 7, in &lt;module&gt;
    from app import MyApp as application
  File &quot;/Users/alan/Sites/combogames/app.py&quot;, line 23, in &lt;module&gt;
    @MyApp.route(&quot;test&quot;)
  File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 1080, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 1043, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File &quot;/usr/local/lib/python2.7/site-packages/werkzeug/routing.py&quot;, line 603, in __init__
    raise ValueError(&apos;urls must start with a leading slash&apos;)
ValueError: urls must start with a leading slash
</pre>

[ 2017-05-09 11:44:18.2537 5960/0x700000290000 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 067b3206. Please see earlier logs for details about the error.
App 5996 stdout: 
App 5996 stderr: Traceback (most recent call last):
App 5996 stderr:   File "/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py", line 325, in <module>
App 5996 stderr:     app_module = load_app()
App 5996 stderr:   File "/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py", line 62, in load_app
App 5996 stderr:     return imp.load_source('passenger_wsgi', startup_file)
App 5996 stderr:   File "/Users/alan/sites/combogames/passenger_wsgi.py", line 7, in <module>
App 5996 stderr:     from app import MyApp as application
App 5996 stderr:   File "/Users/alan/Sites/combogames/app.py", line 23, in <module>
App 5996 stderr:     @MyApp.route("test")
App 5996 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1080, in decorator
App 5996 stderr:     self.add_url_rule(rule, endpoint, f, **options)
App 5996 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 64, in wrapper_func
App 5996 stderr:     return f(self, *args, **kwargs)
App 5996 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1043, in add_url_rule
App 5996 stderr:     rule = self.url_rule_class(rule, methods=methods, **options)
App 5996 stderr:   File "/usr/local/lib/python2.7/site-packages/werkzeug/routing.py", line 603, in __init__
App 5996 stderr:     raise ValueError('urls must start with a leading slash')
App 5996 stderr: ValueError: urls must start with a leading slash
App 5996 stderr: 
[ 2017-05-09 11:44:58.1867 5960/0x7000000c7000 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /Users/alan/sites/combogames: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: 5c5156ed
  Error details saved to: /var/folders/tc/3j3_rt196d7_fz2y5xbz1k1c0000gn/T//passenger-error-StOstZ.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py&quot;, line 325, in &lt;module&gt;
    app_module = load_app()
  File &quot;/usr/local/Cellar/passenger/5.0.26/libexec/src/helper-scripts/wsgi-loader.py&quot;, line 62, in load_app
    return imp.load_source(&apos;passenger_wsgi&apos;, startup_file)
  File &quot;/Users/alan/sites/combogames/passenger_wsgi.py&quot;, line 7, in &lt;module&gt;
    from app import MyApp as application
  File &quot;/Users/alan/Sites/combogames/app.py&quot;, line 23, in &lt;module&gt;
    @MyApp.route(&quot;test&quot;)
  File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 1080, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 1043, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File &quot;/usr/local/lib/python2.7/site-packages/werkzeug/routing.py&quot;, line 603, in __init__
    raise ValueError(&apos;urls must start with a leading slash&apos;)
ValueError: urls must start with a leading slash
</pre>

[ 2017-05-09 11:44:58.1937 5960/0x700000396000 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 3-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 5c5156ed. Please see earlier logs for details about the error.

[ 2017-05-09 11:45:05.3849 5960/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-05-09 11:45:05.3850 5960/0x7fff7a818000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...

[ 2017-05-09 11:45:05.3851 5962/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-05-09 11:45:05.3851 5960/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-05-09 11:45:05.3851 5962/0x7fff7a818000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-05-09 11:45:05.3852 5960/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-05-09 11:45:05.3852 5962/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-05-09 11:45:05.3852 5960/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-05-09 11:45:05.3852 5960/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-05-09 11:45:05.3852 5962/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-05-09 11:45:05.3853 5962/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-05-09 11:45:05.3853 5960/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-05-09 11:45:05.3853 5960/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-05-09 11:45:05.3853 5960/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-05-09 11:45:05.3853 5960/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-05-09 11:45:05.3854 5960/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-05-09 11:45:05.3854 5960/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-05-09 11:45:05.3858 5962/0x7fff7a818000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-05-09 11:45:05.3990 5960/0x7fff7a818000 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-05-09 11:45:06.1950 6019/0x7fff7a818000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-05-09 11:45:06.2128 6021/0x7fff7a818000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-05-09 11:45:06.2142 6021/0x7fff7a818000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-05-09 11:45:06.2205 6021/0x7fff7a818000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 6021
[ 2017-05-09 11:45:06.2282 6023/0x7fff7a818000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-05-09 11:45:06.2297 6023/0x7fff7a818000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 6023
App 6034 stdout: 


[ 2017-05-09 11:46:34.9617 6021/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-05-09 11:46:34.9617 6023/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-05-09 11:46:34.9617 6023/0x7fff7a818000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-05-09 11:46:34.9617 6021/0x7fff7a818000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-05-09 11:46:34.9617 6021/0x7fff7a818000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 6034, application /Users/alan/sites/combogames/public (development)
[ 2017-05-09 11:46:34.9618 6023/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-05-09 11:46:34.9618 6023/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-05-09 11:46:34.9618 6023/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-05-09 11:46:34.9619 6021/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-05-09 11:46:34.9619 6021/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-05-09 11:46:34.9619 6021/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-05-09 11:46:34.9620 6021/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-05-09 11:46:34.9620 6021/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-05-09 11:46:34.9620 6021/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-05-09 11:46:34.9619 6021/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-05-09 11:46:34.9620 6021/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-05-09 11:46:34.9621 6021/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-05-09 11:46:34.9621 6021/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-05-09 11:46:34.9622 6021/0x7fff7a818000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 6034, application /Users/alan/sites/combogames/public (development)
[ 2017-05-09 11:46:34.9625 6023/0x7fff7a818000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-05-09 11:46:35.0757 6021/0x7fff7a818000 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-05-09 11:46:35.5545 6096/0x7fff7a818000 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-05-09 11:46:35.5725 6098/0x7fff7a818000 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-05-09 11:46:35.5739 6098/0x7fff7a818000 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-05-09 11:46:35.5802 6098/0x7fff7a818000 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 6098
[ 2017-05-09 11:46:35.5882 6100/0x7fff7a818000 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-05-09 11:46:35.5899 6100/0x7fff7a818000 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 6100
App 6111 stdout: 

[ 2017-05-09 11:57:13.0664 6098/0x70000018a000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-05-09 11:57:13.0664 6098/0x7fff7a818000 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...

[ 2017-05-09 11:57:13.0665 6100/0x700000104000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-05-09 11:57:13.0665 6098/0x7fff7a818000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 6111, application /Users/alan/sites/combogames/public (development)
[ 2017-05-09 11:57:13.0665 6100/0x7fff7a818000 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-05-09 11:57:13.0666 6100/0x700000104000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-05-09 11:57:13.0666 6100/0x70000020a000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-05-09 11:57:13.0666 6100/0x70000020a000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-05-09 11:57:13.0666 6098/0x70000018a000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-05-09 11:57:13.0667 6098/0x700000290000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-05-09 11:57:13.0667 6098/0x700000290000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-05-09 11:57:13.0668 6098/0x700000396000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-05-09 11:57:13.0668 6098/0x700000396000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-05-09 11:57:13.0668 6098/0x70000049c000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-05-09 11:57:13.0667 6098/0x70000018a000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-05-09 11:57:13.0668 6098/0x70000049c000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-05-09 11:57:13.0669 6098/0x7000005a2000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-05-09 11:57:13.0669 6098/0x7000005a2000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-05-09 11:57:13.0670 6098/0x7fff7a818000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 6111, application /Users/alan/sites/combogames/public (development)
[ 2017-05-09 11:57:13.0673 6100/0x7fff7a818000 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-05-09 11:57:13.1839 6098/0x7fff7a818000 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-06-09 17:22:25.1403 6999/0x7fffebdfe3c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-06-09 17:22:25.1698 7001/0x7fffebdfe3c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-06-09 17:22:25.1722 7001/0x7fffebdfe3c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-06-09 17:22:25.1870 7001/0x7fffebdfe3c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 7001
[ 2017-06-09 17:22:25.1995 7003/0x7fffebdfe3c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-06-09 17:22:25.2027 7003/0x7fffebdfe3c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 7003
App 7018 stdout: 
App 7018 stderr: [2017-06-09 17:22:50,318] ERROR in app: Exception on /_gales_nim [GET]
App 7018 stderr: Traceback (most recent call last):
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 7018 stderr:     response = self.full_dispatch_request()
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 7018 stderr:     rv = self.handle_user_exception(e)
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 7018 stderr:     reraise(exc_type, exc_value, tb)
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 7018 stderr:     rv = self.dispatch_request()
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 7018 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 7018 stderr:   File "/Users/alan/Sites/combogames/app.py", line 210, in gales_nim
App 7018 stderr:     conn = mysql.connect()
App 7018 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 7018 stderr:     return pymysql.connect(**self.connect_args)
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 7018 stderr:     return Connection(*args, **kwargs)
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 7018 stderr:     self.connect()
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 963, in connect
App 7018 stderr:     raise exc
App 7018 stderr: OperationalError: (2003, "Can't connect to MySQL server on 'mysql.combinatoric.games' (timed out)")
App 7018 stderr: [2017-06-09 17:23:00,326] ERROR in app: Exception on /_gales_nim [GET]
App 7018 stderr: Traceback (most recent call last):
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 7018 stderr:     response = self.full_dispatch_request()
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 7018 stderr:     rv = self.handle_user_exception(e)
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 7018 stderr:     reraise(exc_type, exc_value, tb)
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 7018 stderr:     rv = self.dispatch_request()
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 7018 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 7018 stderr:   File "/Users/alan/Sites/combogames/app.py", line 210, in gales_nim
App 7018 stderr:     conn = mysql.connect()
App 7018 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 7018 stderr:     return pymysql.connect(**self.connect_args)
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 7018 stderr:     return Connection(*args, **kwargs)
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 7018 stderr:     self.connect()
App 7018 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 963, in connect
App 7018 stderr:     raise exc
App 7018 stderr: OperationalError: (2003, "Can't connect to MySQL server on 'mysql.combinatoric.games' (timed out)")


[ 2017-06-09 17:37:19.8926 7001/0x700000235000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-06-09 17:37:19.8927 7001/0x7fffebdfe3c0 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-06-09 17:37:19.8927 7003/0x70000c109000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-06-09 17:37:19.8928 7003/0x7fffebdfe3c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-06-09 17:37:19.8930 7001/0x7fffebdfe3c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 7018, application /Users/alan/sites/combogames/public (development)
[ 2017-06-09 17:37:19.8941 7001/0x700000235000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-06-09 17:37:19.8942 7001/0x700000235000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-06-09 17:37:19.8939 7001/0x700000441000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-06-09 17:37:19.8942 7001/0x700000441000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-06-09 17:37:19.8940 7001/0x700000547000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-06-09 17:37:19.8943 7001/0x70000033b000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-06-09 17:37:19.8943 7001/0x70000033b000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-06-09 17:37:19.8943 7001/0x700000547000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-06-09 17:37:19.8942 7003/0x70000c109000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-06-09 17:37:19.8945 7003/0x70000c20f000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-06-09 17:37:19.8946 7003/0x70000c20f000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-06-09 17:37:19.8949 7001/0x70000064d000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-06-09 17:37:19.8951 7001/0x70000064d000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-06-09 17:37:19.8960 7003/0x7fffebdfe3c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-06-09 17:37:19.8960 7001/0x7fffebdfe3c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 7018, application /Users/alan/sites/combogames/public (development)
[ 2017-06-09 17:37:20.0297 7001/0x7fffebdfe3c0 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-10-28 21:07:35.3531 50538/0x7fffe4ac33c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-10-28 21:07:35.3975 50540/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-10-28 21:07:35.3992 50540/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-10-28 21:07:35.4206 50540/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 50540
[ 2017-10-28 21:07:35.4600 50542/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-10-28 21:07:35.4648 50542/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 50542
App 50554 stdout: 
App 50554 stderr: [2017-10-28 21:07:53,105] ERROR in app: Exception on /_check_val [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 154, in check_val
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50554 stderr: [2017-10-28 21:07:53,343] ERROR in app: Exception on /_check_val [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 154, in check_val
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50554 stderr: [2017-10-28 21:07:53,566] ERROR in app: Exception on /_check_val [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 154, in check_val
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50554 stderr: [2017-10-28 21:07:53,783] ERROR in app: Exception on /_check_val [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 154, in check_val
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50554 stderr: [2017-10-28 21:07:54,010] ERROR in app: Exception on /_check_val [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 154, in check_val
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50554 stderr: [2017-10-28 21:07:54,230] ERROR in app: Exception on /_check_val [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 154, in check_val
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50554 stderr: [2017-10-28 21:07:54,446] ERROR in app: Exception on /_check_val [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 154, in check_val
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50554 stderr: [2017-10-28 21:07:54,680] ERROR in app: Exception on /_check_val [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 154, in check_val
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 
App 50554 stderr: 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50554 stderr: [2017-10-28 21:07:54,908] ERROR in app: Exception on /_check_val [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 154, in check_val
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50554 stderr: [2017-10-28 21:07:55,131] ERROR in app: Exception on /_check_val [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 154, in check_val
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50554 stderr: [2017-10-28 21:08:11,896] ERROR in app: Exception on /_gales_nim [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 210, in gales_nim
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50554 stderr: [2017-10-28 21:08:21,332] ERROR in app: Exception on /_gales_nim [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 210, in gales_nim
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50554 stderr: [2017-10-28 21:08:42,456] ERROR in app: Exception on /_gales_nim [GET]
App 50554 stderr: Traceback (most recent call last):
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50554 stderr:     response = self.full_dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50554 stderr:     rv = self.handle_user_exception(e)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50554 stderr:     reraise(exc_type, exc_value, tb)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50554 stderr:     rv = self.dispatch_request()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50554 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50554 stderr:   File "/Users/alan/Sites/combogames/app.py", line 210, in gales_nim
App 50554 stderr:     conn = mysql.connect()
App 50554 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50554 stderr:     return pymysql.connect(**self.connect_args)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50554 stderr:     return Connection(*args, **kwargs)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50554 stderr:     self.connect()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50554 stderr:     self._request_authentication()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50554 stderr:     auth_packet = self._read_packet()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50554 stderr:     packet.check_error()
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50554 stderr:     err.raise_mysql_exception(self._data)
App 50554 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50554 stderr:     raise errorclass(errno, errval)
App 50554 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")


[ 2017-10-28 21:08:47.2888 50540/0x700009d05000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:08:47.2888 50542/0x70000b43f000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:08:47.2888 50540/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:08:47.2888 50542/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:08:47.2889 50540/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 50554, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:08:47.2891 50540/0x700009d05000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-10-28 21:08:47.2891 50542/0x70000b43f000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-10-28 21:08:47.2891 50540/0x700009d05000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-10-28 21:08:47.2891 50542/0x70000b545000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-10-28 21:08:47.2891 50542/0x70000b545000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-10-28 21:08:47.2892 50540/0x700009e0b000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-10-28 21:08:47.2892 50540/0x700009e0b000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-10-28 21:08:47.2893 50540/0x700009f11000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-10-28 21:08:47.2893 50540/0x700009f11000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-10-28 21:08:47.2895 50540/0x70000a017000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-10-28 21:08:47.2895 50540/0x70000a017000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-10-28 21:08:47.2896 50540/0x70000a11d000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-10-28 21:08:47.2896 50540/0x70000a11d000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-10-28 21:08:47.2897 50540/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 50554, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:08:47.2917 50542/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-10-28 21:08:47.4072 50540/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-10-28 21:08:48.4365 50616/0x7fffe4ac33c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-10-28 21:08:48.4716 50618/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-10-28 21:08:48.4750 50618/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-10-28 21:08:48.4942 50618/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 50618
[ 2017-10-28 21:08:48.5104 50620/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-10-28 21:08:48.5123 50620/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 50620
App 50632 stdout: 
App 50632 stderr: [2017-10-28 21:08:53,076] ERROR in app: Exception on /_gales_nim [GET]
App 50632 stderr: Traceback (most recent call last):
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50632 stderr:     response = self.full_dispatch_request()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50632 stderr:     rv = self.handle_user_exception(e)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50632 stderr:     reraise(exc_type, exc_value, tb)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50632 stderr:     rv = self.dispatch_request()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50632 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50632 stderr:   File "/Users/alan/Sites/combogames/app.py", line 210, in gales_nim
App 50632 stderr:     conn = mysql.connect()
App 50632 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50632 stderr:     return pymysql.connect(**self.connect_args)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50632 stderr:     return Connection(*args, **kwargs)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50632 stderr:     self.connect()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50632 stderr:     self._request_authentication()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50632 stderr:     auth_packet = self._read_packet()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50632 stderr:     packet.check_error()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50632 stderr:     err.raise_mysql_exception(self._data)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50632 stderr:     raise errorclass(errno, errval)
App 50632 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50632 stderr: [2017-10-28 21:10:06,282] ERROR in app: Exception on /_gales_nim [GET]
App 50632 stderr: Traceback (most recent call last):
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50632 stderr:     response = self.full_dispatch_request()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50632 stderr:     rv = self.handle_user_exception(e)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50632 stderr:     reraise(exc_type, exc_value, tb)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50632 stderr:     rv = self.dispatch_request()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50632 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50632 stderr:   File "/Users/alan/Sites/combogames/app.py", line 210, in gales_nim
App 50632 stderr:     conn = mysql.connect()
App 50632 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50632 stderr:     return pymysql.connect(**self.connect_args)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50632 stderr:     return Connection(*args, **kwargs)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50632 stderr:     self.connect()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50632 stderr:     self._request_authentication()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50632 stderr:     auth_packet = self._read_packet()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50632 stderr:     packet.check_error()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50632 stderr:     err.raise_mysql_exception(self._data)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50632 stderr:     raise errorclass(errno, errval)
App 50632 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")
App 50632 stderr: [2017-10-28 21:10:12,451] ERROR in app: Exception on /_gales_nim [GET]
App 50632 stderr: Traceback (most recent call last):
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
App 50632 stderr:     response = self.full_dispatch_request()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
App 50632 stderr:     rv = self.handle_user_exception(e)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
App 50632 stderr:     reraise(exc_type, exc_value, tb)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
App 50632 stderr:     rv = self.dispatch_request()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
App 50632 stderr:     return self.view_functions[rule.endpoint](**req.view_args)
App 50632 stderr:   File "/Users/alan/Sites/combogames/app.py", line 210, in gales_nim
App 50632 stderr:     conn = mysql.connect()
App 50632 stderr:   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flaskext/mysql.py", line 53, in connect
App 50632 stderr:     return pymysql.connect(**self.connect_args)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
App 50632 stderr:     return Connection(*args, **kwargs)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
App 50632 stderr:     self.connect()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 932, in connect
App 50632 stderr:     self._request_authentication()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1152, in _request_authentication
App 50632 stderr:     auth_packet = self._read_packet()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
App 50632 stderr:     packet.check_error()
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
App 50632 stderr:     err.raise_mysql_exception(self._data)
App 50632 stderr:   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
App 50632 stderr:     raise errorclass(errno, errval)
App 50632 stderr: OperationalError: (1045, u"Access denied for user 'combogames'@'192.83.228.246' (using password: YES)")

[ 2017-10-28 21:10:14.8163 50618/0x700008918000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)

[ 2017-10-28 21:10:14.8164 50618/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:10:14.8164 50620/0x700009395000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:10:14.8164 50618/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 50632, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:10:14.8165 50620/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:10:14.8166 50620/0x700009395000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-10-28 21:10:14.8167 50620/0x70000949b000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-10-28 21:10:14.8167 50620/0x70000949b000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-10-28 21:10:14.8167 50618/0x700008918000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-10-28 21:10:14.8168 50618/0x700008918000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-10-28 21:10:14.8168 50618/0x700008a1e000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-10-28 21:10:14.8170 50618/0x700008b24000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-10-28 21:10:14.8171 50618/0x700008c2a000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-10-28 21:10:14.8171 50618/0x700008a1e000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-10-28 21:10:14.8171 50618/0x700008b24000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-10-28 21:10:14.8171 50618/0x700008c2a000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-10-28 21:10:14.8172 50618/0x700008d30000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-10-28 21:10:14.8172 50618/0x700008d30000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-10-28 21:10:14.8173 50618/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 50632, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:10:14.8184 50620/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-10-28 21:10:14.9330 50618/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-10-28 21:10:15.8161 50696/0x7fffe4ac33c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-10-28 21:10:15.8594 50698/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-10-28 21:10:15.8608 50698/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-10-28 21:10:15.8747 50698/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 50698
[ 2017-10-28 21:10:15.8827 50700/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-10-28 21:10:15.8845 50700/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 50700
App 50714 stdout: 
App 50725 stdout: 


[ 2017-10-28 21:13:04.1021 50698/0x70000fcf4000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:13:04.1021 50700/0x700009041000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:13:04.1022 50700/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:13:04.1022 50698/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:13:04.1022 50698/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 50714, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:13:04.1022 50700/0x700009041000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-10-28 21:13:04.1023 50698/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 50725, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:13:04.1023 50700/0x700009147000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-10-28 21:13:04.1023 50700/0x700009147000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-10-28 21:13:04.1024 50698/0x70000fcf4000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-10-28 21:13:04.1024 50698/0x70000fdfa000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-10-28 21:13:04.1024 50698/0x70000fcf4000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-10-28 21:13:04.1025 50698/0x70000fdfa000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-10-28 21:13:04.1026 50698/0x70000ff00000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-10-28 21:13:04.1026 50698/0x700010006000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-10-28 21:13:04.1026 50698/0x700010006000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-10-28 21:13:04.1026 50698/0x70000ff00000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-10-28 21:13:04.1027 50698/0x70001010c000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-10-28 21:13:04.1027 50698/0x70001010c000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-10-28 21:13:04.1028 50698/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 50714, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:13:04.1028 50698/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 50725, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:13:04.1069 50700/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-10-28 21:13:04.2218 50698/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-10-28 21:15:36.0925 50877/0x7fffe4ac33c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-10-28 21:15:36.1320 50879/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-10-28 21:15:36.1346 50879/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-10-28 21:15:36.1411 50879/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 50879
[ 2017-10-28 21:15:36.1494 50881/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-10-28 21:15:36.1513 50881/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 50881
App 50892 stdout: 
App 50904 stdout: 


[ 2017-10-28 21:18:12.4711 50879/0x7000073f2000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:18:12.4711 50881/0x700002b5f000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:18:12.4712 50879/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:18:12.4712 50881/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:18:12.4712 50879/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 50892, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:18:12.4713 50881/0x700002c65000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-10-28 21:18:12.4713 50879/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 50904, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:18:12.4713 50881/0x700002c65000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-10-28 21:18:12.4713 50881/0x700002b5f000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-10-28 21:18:12.4715 50879/0x7000073f2000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-10-28 21:18:12.4716 50879/0x7000074f8000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-10-28 21:18:12.4716 50879/0x7000073f2000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-10-28 21:18:12.4716 50879/0x7000074f8000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-10-28 21:18:12.4718 50879/0x7000075fe000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-10-28 21:18:12.4719 50879/0x7000075fe000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-10-28 21:18:12.4719 50879/0x700007704000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-10-28 21:18:12.4719 50879/0x700007704000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-10-28 21:18:12.4719 50879/0x70000780a000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-10-28 21:18:12.4720 50879/0x70000780a000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-10-28 21:18:12.4721 50879/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 50892, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:18:12.4721 50879/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 50904, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:18:12.4729 50881/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-10-28 21:18:12.5881 50879/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-10-28 21:18:13.2275 51009/0x7fffe4ac33c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-10-28 21:18:13.2778 51011/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-10-28 21:18:13.2795 51011/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-10-28 21:18:13.2974 51011/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 51011
[ 2017-10-28 21:18:13.3054 51013/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-10-28 21:18:13.3071 51013/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 51013
App 51024 stdout: 


[ 2017-10-28 21:29:45.0910 51013/0x7000026d4000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:29:45.0910 51013/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:29:45.0911 51013/0x7000026d4000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-10-28 21:29:45.0912 51011/0x700005794000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:29:45.0912 51013/0x7000027da000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-10-28 21:29:45.0912 51013/0x7000027da000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-10-28 21:29:45.0915 51011/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:29:45.0915 51011/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51024, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:29:45.0918 51011/0x7000059a0000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-10-28 21:29:45.0918 51011/0x7000059a0000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-10-28 21:29:45.0919 51011/0x700005794000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-10-28 21:29:45.0919 51011/0x700005aa6000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-10-28 21:29:45.0919 51011/0x700005aa6000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-10-28 21:29:45.0919 51011/0x700005794000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-10-28 21:29:45.0920 51011/0x70000589a000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-10-28 21:29:45.0920 51011/0x70000589a000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-10-28 21:29:45.0920 51011/0x700005bac000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-10-28 21:29:45.0920 51011/0x700005bac000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-10-28 21:29:45.0921 51011/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51024, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:29:45.0925 51013/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-10-28 21:29:45.2067 51011/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-10-28 21:29:45.7787 51414/0x7fffe4ac33c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-10-28 21:29:45.8036 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-10-28 21:29:45.8050 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-10-28 21:29:45.8113 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 51416
[ 2017-10-28 21:29:45.8198 51418/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-10-28 21:29:45.8218 51418/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 51418
App 51430 stdout: 
App 51442 stdout: 
App 51463 stdout: 
App 51474 stdout: 
App 51430 stdout: 0
App 51430 stdout: 
App 51442 stdout: 1
App 51463 stdout: 1
App 51474 stdout: 1
App 51474 stdout: 
App 51430 stdout: 0


[ 2017-10-28 21:30:17.8392 51418/0x70000267a000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:30:17.8392 51416/0x70000e1cd000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:30:17.8393 51418/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:30:17.8393 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:30:17.8393 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51430, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:30:17.8393 51418/0x70000267a000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-10-28 21:30:17.8393 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51442, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:30:17.8394 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51463, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:30:17.8394 51418/0x700002780000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-10-28 21:30:17.8394 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51474, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:30:17.8394 51418/0x700002780000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-10-28 21:30:17.8396 51416/0x70000e2d3000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-10-28 21:30:17.8396 51416/0x70000e1cd000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-10-28 21:30:17.8397 51416/0x70000e2d3000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-10-28 21:30:17.8397 51416/0x70000e3d9000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-10-28 21:30:17.8398 51416/0x70000e4df000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-10-28 21:30:17.8398 51416/0x70000e1cd000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-10-28 21:30:17.8398 51416/0x70000e5e5000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-10-28 21:30:17.8398 51416/0x70000e3d9000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-10-28 21:30:17.8398 51416/0x70000e4df000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-10-28 21:30:17.8399 51416/0x70000e5e5000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-10-28 21:30:17.8399 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51430, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:30:17.8400 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51442, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:30:17.8400 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51463, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:30:17.8400 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51474, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:30:17.8404 51418/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-10-28 21:30:17.9607 51416/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-10-28 21:30:21.9099 51505/0x7fffe4ac33c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-10-28 21:30:21.9439 51507/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-10-28 21:30:21.9455 51507/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-10-28 21:30:21.9574 51507/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 51507
[ 2017-10-28 21:30:21.9738 51509/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-10-28 21:30:21.9758 51509/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 51509
App 51520 stdout: 
App 51532 stdout: 
App 51520 stdout: 0
[ 2017-10-28 21:35:24.5724 51507/0x70000db07000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51532, application /Users/alan/sites/combogames/public (development)

[ 2017-10-28 21:58:22.8884 51507/0x70000dc0d000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:58:22.8884 51507/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:58:22.8885 51507/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51520, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:58:22.8887 51507/0x70000dc0d000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects

[ 2017-10-28 21:58:22.8890 51509/0x70000c939000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-28 21:58:22.8891 51509/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-28 21:58:22.8892 51509/0x70000c939000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-10-28 21:58:22.8893 51509/0x70000ca3f000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-10-28 21:58:22.8893 51509/0x70000ca3f000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-10-28 21:58:22.8900 51507/0x70000dd13000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-10-28 21:58:22.8900 51507/0x70000dd13000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-10-28 21:58:22.8901 51507/0x70000de19000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-10-28 21:58:22.8902 51507/0x70000de19000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-10-28 21:58:22.8902 51507/0x70000df1f000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-10-28 21:58:22.8903 51507/0x70000dc0d000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-10-28 21:58:22.8903 51507/0x70000df1f000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-10-28 21:58:22.8904 51507/0x70000e025000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-10-28 21:58:22.8904 51507/0x70000e025000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-10-28 21:58:22.8904 51507/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 51520, application /Users/alan/sites/combogames/public (development)
[ 2017-10-28 21:58:22.8915 51509/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-10-28 21:58:23.0084 51507/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-10-28 21:58:23.9463 52507/0x7fffe4ac33c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-10-28 21:58:23.9680 52509/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-10-28 21:58:23.9695 52509/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-10-28 21:58:23.9766 52509/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 52509
[ 2017-10-28 21:58:23.9843 52511/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-10-28 21:58:23.9861 52511/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 52511
App 52523 stdout: 
App 52535 stdout: 
[ 2017-10-28 22:03:28.8209 52509/0x7000078ad000 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 52535, application /Users/alan/sites/combogames/public (development)


[ 2017-10-29 08:31:28.4310 52509/0x7000079b3000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-29 08:31:28.4310 52511/0x700008d4b000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-29 08:31:28.4315 52511/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-29 08:31:28.4315 52509/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-29 08:31:28.4316 52509/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 52523, application /Users/alan/sites/combogames/public (development)
[ 2017-10-29 08:31:28.4316 52511/0x700008d4b000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-10-29 08:31:28.4317 52511/0x700008e51000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-10-29 08:31:28.4317 52511/0x700008e51000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-10-29 08:31:28.4321 52509/0x700007ab9000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-10-29 08:31:28.4322 52509/0x700007bbf000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-10-29 08:31:28.4322 52509/0x700007ab9000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-10-29 08:31:28.4322 52509/0x700007bbf000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-10-29 08:31:28.4322 52509/0x7000079b3000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-10-29 08:31:28.4322 52509/0x7000079b3000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-10-29 08:31:28.4323 52509/0x700007dcb000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-10-29 08:31:28.4323 52509/0x700007dcb000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-10-29 08:31:28.4324 52509/0x700007cc5000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-10-29 08:31:28.4324 52509/0x700007cc5000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-10-29 08:31:28.4325 52509/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 52523, application /Users/alan/sites/combogames/public (development)
[ 2017-10-29 08:31:28.4329 52511/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-10-29 08:31:28.5526 52509/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-10-29 08:31:33.5263 60569/0x7fffe4ac33c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-10-29 08:31:33.5530 60571/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-10-29 08:31:33.5552 60571/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-10-29 08:31:33.5638 60571/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 60571
[ 2017-10-29 08:31:33.5751 60573/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-10-29 08:31:33.5781 60573/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 60573
App 60584 stdout: 
App 60597 stdout: 


[ 2017-10-29 08:32:24.6814 60573/0x700002f06000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-29 08:32:24.6814 60571/0x700008b12000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-29 08:32:24.6815 60573/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-29 08:32:24.6815 60573/0x70000300c000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-10-29 08:32:24.6815 60573/0x700002f06000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-10-29 08:32:24.6815 60571/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-29 08:32:24.6815 60573/0x70000300c000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-10-29 08:32:24.6816 60571/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 60584, application /Users/alan/sites/combogames/public (development)
[ 2017-10-29 08:32:24.6816 60571/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 60597, application /Users/alan/sites/combogames/public (development)
[ 2017-10-29 08:32:24.6818 60571/0x700008b12000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-10-29 08:32:24.6818 60571/0x700008b12000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-10-29 08:32:24.6818 60571/0x700008c18000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-10-29 08:32:24.6818 60571/0x700008c18000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-10-29 08:32:24.6819 60571/0x700008d1e000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-10-29 08:32:24.6819 60571/0x700008e24000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-10-29 08:32:24.6820 60571/0x700008e24000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-10-29 08:32:24.6819 60571/0x700008d1e000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-10-29 08:32:24.6820 60571/0x700008f2a000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-10-29 08:32:24.6820 60571/0x700008f2a000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-10-29 08:32:24.6821 60571/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 60584, application /Users/alan/sites/combogames/public (development)
[ 2017-10-29 08:32:24.6821 60571/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 60597, application /Users/alan/sites/combogames/public (development)
[ 2017-10-29 08:32:24.6832 60573/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-10-29 08:32:24.7996 60571/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-10-29 08:32:25.3232 60649/0x7fffe4ac33c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-10-29 08:32:25.3453 60651/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-10-29 08:32:25.3467 60651/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-10-29 08:32:25.3529 60651/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 60651
[ 2017-10-29 08:32:25.3603 60653/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-10-29 08:32:25.3621 60653/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 60653
App 60664 stdout: 


[ 2017-10-29 08:32:41.1104 60651/0x7000009a1000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-29 08:32:41.1104 60653/0x70000817f000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-29 08:32:41.1105 60653/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-29 08:32:41.1105 60651/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-29 08:32:41.1105 60651/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 60664, application /Users/alan/sites/combogames/public (development)
[ 2017-10-29 08:32:41.1106 60653/0x700008285000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-10-29 08:32:41.1106 60653/0x700008285000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-10-29 08:32:41.1106 60653/0x70000817f000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-10-29 08:32:41.1109 60651/0x700000aa7000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-10-29 08:32:41.1109 60651/0x7000009a1000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-10-29 08:32:41.1109 60651/0x700000aa7000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-10-29 08:32:41.1110 60651/0x700000bad000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-10-29 08:32:41.1111 60651/0x7000009a1000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-10-29 08:32:41.1111 60651/0x700000cb3000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-10-29 08:32:41.1111 60651/0x700000bad000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-10-29 08:32:41.1112 60651/0x700000cb3000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-10-29 08:32:41.1112 60651/0x700000db9000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-10-29 08:32:41.1113 60651/0x700000db9000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-10-29 08:32:41.1113 60651/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 60664, application /Users/alan/sites/combogames/public (development)
[ 2017-10-29 08:32:41.1125 60653/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-10-29 08:32:41.2304 60651/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2017-10-29 08:32:41.7092 60697/0x7fffe4ac33c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2017-10-29 08:32:41.7383 60699/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2017-10-29 08:32:41.7401 60699/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2017-10-29 08:32:41.7509 60699/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 60699
[ 2017-10-29 08:32:41.7649 60701/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2017-10-29 08:32:41.7696 60701/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 60701
App 60712 stdout: 


[ 2017-10-29 12:13:55.7388 60701/0x70000676b000 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-29 12:13:55.7390 60699/0x70000564f000 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2017-10-29 12:13:55.7395 60701/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-29 12:13:55.7395 60699/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2017-10-29 12:13:55.7400 60701/0x70000676b000 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2017-10-29 12:13:55.7401 60701/0x700006871000 Ser/Server.h:816 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2017-10-29 12:13:55.7402 60701/0x700006871000 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2017-10-29 12:13:55.7396 60699/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 60712, application /Users/alan/sites/combogames/public (development)
[ 2017-10-29 12:13:55.7412 60699/0x70000564f000 Ser/Server.h:816 ]: [ServerThr.1] Freed 128 spare client objects
[ 2017-10-29 12:13:55.7413 60699/0x70000564f000 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2017-10-29 12:13:55.7415 60699/0x700005755000 Ser/Server.h:816 ]: [ServerThr.2] Freed 128 spare client objects
[ 2017-10-29 12:13:55.7415 60699/0x700005755000 Ser/Server.h:464 ]: [ServerThr.2] Shutdown finished
[ 2017-10-29 12:13:55.7418 60699/0x70000585b000 Ser/Server.h:816 ]: [ServerThr.3] Freed 128 spare client objects
[ 2017-10-29 12:13:55.7418 60699/0x70000585b000 Ser/Server.h:464 ]: [ServerThr.3] Shutdown finished
[ 2017-10-29 12:13:55.7418 60699/0x700005961000 Ser/Server.h:816 ]: [ServerThr.4] Freed 128 spare client objects
[ 2017-10-29 12:13:55.7419 60699/0x700005961000 Ser/Server.h:464 ]: [ServerThr.4] Shutdown finished
[ 2017-10-29 12:13:55.7421 60699/0x700005a67000 Ser/Server.h:816 ]: [ApiServer] Freed 0 spare client objects
[ 2017-10-29 12:13:55.7421 60699/0x700005a67000 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2017-10-29 12:13:55.7422 60699/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 60712, application /Users/alan/sites/combogames/public (development)
[ 2017-10-29 12:13:55.7430 60701/0x7fffe4ac33c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2017-10-29 12:13:55.8570 60699/0x7fffe4ac33c0 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
